services:
  dev:
    image: ghcr.io/ssongin/devcontainer:1.8.1
    container_name: dev
    stdin_open: true
    tty: true
    volumes:
      - "C:/Users/ssong/Projects:/home/user/projects"
      - "C:/Users/ssong/.kube:/home/user/.kube"
      - "C:/Users/ssong/.ssh:/home/user/.ssh"
      - dev_cache:/root/.cache
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    working_dir: /home/user/projects
    network_mode: bridge
    restart: unless-stopped
    command: >
      sh -c "
      sudo chown -R user:user /home/user &&
      chmod 700 /home/user/.ssh &&
      chmod 600 /home/user/.ssh/* 2>/dev/null || true &&
      chmod -R 755 /home/user/projects/ || true &&
      exec zsh
      "


# --- SEMAPHORE --- #
  # Postgres database service for semaphore UI
  #postgres:
    #restart: unless-stopped
    #image: postgres:14
    #hostname: postgres
    #volumes:
    #  - semaphore-postgres:/var/lib/postgresql/data
    #environment:
    #  POSTGRES_USER: semaphore
    #  POSTGRES_PASSWORD: semaphore
    #  POSTGRES_DB: semaphore
  # MySQL database service for semaphore UI
  # mysql:
  #   restart: unless-stopped
  #   image: mysql:8.0
  #   hostname: mysql
  #   volumes:
  #     - semaphore-mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  #     MYSQL_DATABASE: semaphore
  #     MYSQL_USER: semaphore
  #     MYSQL_PASSWORD: semaphore
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    volumes:
      - semaphore-etc:/etc/semaphore
      - semaphore-data:/var/lib/semaphore
      - "C:/Users/ssong/Projects:/home/semaphore/projects"
    environment:
      # SEMAPHORE_DB_USER: semaphore
      # SEMAPHORE_DB_PASS: semaphore
      # SEMAPHORE_DB_HOST: mysql # for mysql
      # SEMAPHORE_DB_HOST: postgres # for postgres
      # SEMAPHORE_DB_PORT: 3306 # MySQL port
      # SEMAPHORE_DB_PORT: 5432 # Postgres port
      # SEMAPHORE_DB_DIALECT: mysql 
      # SEMAPHORE_DB_DIALECT: postgres
      # SEMAPHORE_DB_DIALECT: mysql
      # SEMAPHORE_DB: semaphore
      # To use SQLite instead of MySQL/Postgres (v2.16+)
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_DB: "/etc/semaphore/semaphore.sqlite"
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes'
      SEMAPHORE_LDAP_HOST: dc01.local.example.com
      SEMAPHORE_LDAP_PORT: '636'
      SEMAPHORE_LDAP_NEEDTLS: 'yes'
      SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
      SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
      SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
      SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
      TZ: Europe/Vilnius
    # depends_on:
    #   - mysql # for mysql
    #   - postgres # for postgres
volumes:
  dev_cache: # for dev conatiner cache
  # semaphore-mysql: # for semaphore database when using mysql
  # semaphore-postgres: # for semaphore database when using postgres
  semaphore-etc:
  semaphore-data: